version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: chatapp2
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network_progjar

  chatserver:
    image: python:3.12.4-alpine3.19 
    restart: unless-stopped
    volumes:
      - ./app/server:/app
    environment: 
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8889
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=chatapp2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_PORT=3306
    working_dir: /app
    ports:
      - 8889:8889
    command:
      - /bin/sh
      - -c
      - 'cd /app && pip3 install -r requirements.txt && python3 server.py'
    networks:
      - network_progjar

  chatclient:
    image: python:3.12.4-alpine3.19 
    restart: unless-stopped
    environment:
      - SERVER_IP=172.222.221.3
      - SERVER_PORT=8889
      - ONWEB=1
    working_dir: /app
    ports:
      - 8550:8550
    volumes:
      - ./app/client:/app
    command:
      - /bin/sh
      - -c
      - 'cd /app && pip3 install -r requirements.txt && python3 chat-flet.py'
    depends_on:
      - chatserver
    networks:
      - network_progjar

networks:
  network_progjar:
    ipam:
      config:
        - subnet: 172.222.221.0/24

volumes:
  mysql-data:
